# Generated by Django 2.2.10 on 2022-02-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220224_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='_labour',
            field=models.BooleanField(default=False),
        ),
    ]
