# Generated by Django 2.2.10 on 2022-02-24 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labour',
            name='address',
            field=models.CharField(default='Noida sector 22', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labour',
            name='mobile',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(10)]),
        ),
    ]
